### ISSUE TITLE
CV Genie Roadmap

### ISSUE THREAD

**Issue by Kautenja** [Kautenja/RackNES#47]
The CV Genie (input) module is under development with the following bucketlist / roadmap of issues to address.

### Open Issues

- [ ] moar knobs!
    - some knobs to control the parameters without CV would be fun
    - an input attenuator / attenuverter would be nice for scaling CV inputs
- [ ] determine whether using trademarked title names will be a problem (I think it's probably fine so long as the `TM` is listed?, i.e. Super Mario Bros.™)
- [ ] support for multi-RAM-slot parameters
    - some application level parameters use multiple RAM slots. How should this be addressed?
        1. the memory map data structure could be changed to map a single CV to multiple slots
        2. the module could allow chain-able inputs (i.e., optional input normalling) to connect CV inputs together
- [x] find a way for the memory bus of the emulator to be accessible in a well defined manner
    - it's public at the moment, which is a code smell, refactoring is needed
- [x] fix triggers for switched parameters
    - sometimes trigger inputs require multiple triggers. This may just require scaling the voltage to the input Schmidt trigger. More review is needed.
- [ ] clamp parameters to prevent undefined behavior from "clipped" inputs
    - clipping is symbolic, `V > 10` implies clipping in VCV Rack. The input to the module is quantized and encoded to 8-bit and thus needs clipped to `[-10, 10V]`
- [ ] support more games
    - ~~this can probably be handled semi-automated by scraping a RAM map repository and generating C++ structs from tabular data. Some human review will be necessary.~~
    - the format for reporting the RAM maps is not necessarily standardized, they will need to be done by hand
    - https://datacrystal.romhacking.net/wiki/Category:RAM_maps

### Graveyard

- **automatic game detection.** There is no well-defined way to map a ROM file to an NES title because the file format does not identify the games. Checksums are ineffective because small variations in ROM file for the same title will produce different checksums (including minor ROM hacks).
- **parameter displays.** IMO the value of the parameter in binary isn't very useful or interesting to know. There is a linear relationship between the voltage and the parameter, so an oscilloscope can effectively provide this for input and output signals really. There are special cases for triggers and parameters with small ranges, but as of right now this feature seems unnecessary.
- **arbitrary RAM addressing** This feature would allow for plenty of accidental discoveries, but would not be very useful for accomplishing semantic tasks (i.e., make Mario move around in a circle). Additionally, it stands to frequently crash the game by writing invalid values to invalid addresses. IMO, it could be an interesting feature, but seems not worth the trouble.

**Comment by Kautenja** [comment]
MemoryBus was made private by use of the `get_memory_buffer` function that returns a pointer to the 8-bit RAM.

**Comment by Kautenja** [comment]
Bug: when switching games, if a hack is selected with an index greater than the index of hacks available for the selected game, the screen gets messed up and saving / loading JSON state gets messed up.

**Comment by flarn2006** [comment]
I don't see how arbitrary RAM addressing isn't worth the trouble. The crashing could easily be worked around in a patch by wiring a clock to the RackNES's "LOAD" input, after saving a state with the game working.

**Comment by Kautenja** [comment]
PRs are welcome
